#!/usr/bin/env bash
# scripts/preflight.sh — local reproduction of the CI gates before `git push`.
# Generated by ~/claude-config/scripts/gen-preflight.py from the workflows below;
# every command is the one CI runs. A step this file does not cover is a step
# that can only fail remotely — when a workflow step is added, regenerate or
# add it here in the same commit. ~/.claude/hooks/pre-push-preflight.sh runs
# `--quick` before every push and blocks on failure.
#
# usage: scripts/preflight.sh [--quick]   (--quick skips the test / bench suites)
set -euo pipefail
cd "$(dirname "$0")/.."

quick=0
[[ "${1:-}" == "--quick" ]] && quick=1

step() { printf '\n\033[1;34m== %s\033[0m\n' "$*"; }
# `cargo clippy` reuses fresh `cargo check` artifacts and then lints nothing;
# touching the crate roots invalidates only this repo's fingerprints.
relint() { git ls-files | grep -E '(^|/)src/(lib|main)\.rs$' | xargs -r touch; }
need() { command -v "$1" >/dev/null 2>&1 || { echo "missing tool: $1 ($2)" >&2; exit 1; }; }
has_toolchain() { rustup toolchain list | grep -q "^$1"; }

# Steps CI runs that this file cannot reproduce locally (they can only fail remotely):
#   - ci.yml:audit:Install cargo-audit (needs network / runner-only)
#   - ci.yml:clippy-test-doc:Install libdbus-1-dev (Linux only) (no cargo / grep)
#   - security-audit.yml:deny:Install cargo-deny (needs network / runner-only)
#   - security-audit.yml:coverage (job is continue-on-error: informational in CI)
#   - security-audit.yml:semver-checks (job is continue-on-error: informational in CI)
#   - fuzz.yml:fuzz (job is continue-on-error: informational in CI)

need cargo-audit "cargo install cargo-audit --locked"
need cargo-deny "cargo install cargo-deny --locked"
need cargo-machete "cargo install cargo-machete --locked"

step "ci.yml / clippy-test-doc: cargo fmt --check"
( export CARGO_TERM_COLOR="always"; cargo fmt --all -- --check )

step "ci.yml / clippy-test-doc: cargo clippy (workspace, all targets)"
relint
( export CARGO_TERM_COLOR="always"; cargo clippy --workspace --all-targets -- -D warnings )

step "ci.yml / clippy-test-doc: cargo doc (no deps)"
( export CARGO_TERM_COLOR="always" RUSTDOCFLAGS="-D warnings"; cargo doc --workspace --no-deps )

step "ci.yml / check-wasm-worker: cargo check --target wasm32-unknown-unknown"
rustup target list --installed | grep -q '^wasm32-unknown-unknown$' || rustup target add wasm32-unknown-unknown
(cd "crates/worker" && ( export CARGO_TERM_COLOR="always"; cargo check --target wasm32-unknown-unknown --release ))

step "security-audit.yml / deny: Run cargo deny check all"
( export CARGO_TERM_COLOR="always" CARGO_NET_RETRY="5" CARGO_HTTP_MULTIPLEXING="false"; cargo deny --all-features check all )

step "security-audit.yml / unused-deps: cargo machete"
cargo machete

step "security-audit.yml / stub-guard: Detect todo! / unimplemented! / panic!(STUB) in src/**"
(
  export CARGO_TERM_COLOR="always" CARGO_NET_RETRY="5" CARGO_HTTP_MULTIPLEXING="false"
  set -eo pipefail
  hits=$(grep -rnE 'todo!\(|unimplemented!\(|panic!\([^)]*STUB' \
    crates/ --include="*.rs" \
    --exclude-dir=bin \
    --exclude-dir=target \
    || true)
  if [ -n "$hits" ]; then
    echo "❌ Stub / unimplemented / STUB panic detected in production path:"
    echo "$hits"
    exit 1
  fi
  echo "✓ No todo! / unimplemented! / panic!(STUB) in crates/"
)

step "security-audit.yml / stub-guard: Detect dbg!() residual"
(
  export CARGO_TERM_COLOR="always" CARGO_NET_RETRY="5" CARGO_HTTP_MULTIPLEXING="false"
  set -eo pipefail
  hits=$(grep -rn 'dbg!(' crates/ --include="*.rs" \
    --exclude-dir=target || true)
  if [ -n "$hits" ]; then
    echo "❌ dbg!() macro left in crates/:"
    echo "$hits"
    exit 1
  fi
  echo "✓ No dbg!() in crates/"
)

step "security-audit.yml / stub-guard: Detect TODO / FIXME / XXX / HACK (informational)"
(
  export CARGO_TERM_COLOR="always" CARGO_NET_RETRY="5" CARGO_HTTP_MULTIPLEXING="false"
  set -eo pipefail
  hits=$(grep -rnE 'TODO|FIXME|XXX|HACK' crates/ --include="*.rs" \
    --exclude-dir=target || true)
  if [ -n "$hits" ]; then
    echo "::warning::TODO/FIXME/XXX/HACK found (informational):"
    echo "$hits" | head -50
  else
    echo "✓ No TODO/FIXME/XXX/HACK in crates/"
  fi
)

step "fuzz.yml / build every fuzz target (nightly; the replay needs the runner)"
if has_toolchain nightly && cargo +nightly fuzz --version >/dev/null 2>&1; then
  (cd fuzz && cargo +nightly fuzz build)
else
  echo "skip: nightly / cargo-fuzz not installed" >&2
fi

if [[ $quick -eq 1 ]]; then
  echo; echo "preflight --quick OK (test / bench suites skipped)"; exit 0
fi

step "ci.yml / audit: cargo audit (honours .cargo/audit.toml ignore list)"
( export CARGO_TERM_COLOR="always"; cargo audit )

step "ci.yml / clippy-test-doc: cargo test (workspace lib)"
( export CARGO_TERM_COLOR="always"; cargo test --workspace --lib )

echo; echo "preflight OK"
